pipeline {
    agent any

    environment {
        IMAGE_NAME = "rishiraj570/myapp"
    }

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/rishiraj570/containerization-devops-.git'
            }
        }

        stage('Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME:latest EXP7/'
            }
        }

        stage('Login') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {
                    sh 'echo $DOCKER_TOKEN | docker login -u rishiraj570 --password-stdin'
                }
            }
        }

        stage('Push') {
            steps {
                sh 'docker push $IMAGE_NAME:latest'
            }
        }
    }
}
